module.exports = {
  root: true,
  parser: '@typescript-eslint/parser',
  plugins: ['@typescript-eslint', 'jsdoc', 'filename-rules', 'prettier', 'promise'],
  extends: ['eslint:recommended', 'plugin:@typescript-eslint/recommended', 'prettier'],
  ignorePatterns: [
    'sentry.client.config.js',
    'sentry.client.server.js',
    '.eslintrc.js',
  ],
  rules: {
    '@typescript-eslint/ban-ts-comment': 'warn',
    '@typescript-eslint/ban-types': 'warn',
    '@typescript-eslint/no-empty-function': 'off',
    '@typescript-eslint/no-empty-interface': 'warn',
    '@typescript-eslint/no-explicit-any': 'off',
    '@typescript-eslint/no-explicit-any': 'warn',
    '@typescript-eslint/no-inferrable-types': 'warn',
    '@typescript-eslint/no-namespace': 'warn',
    '@typescript-eslint/no-non-null-assertion': 'off',
    '@typescript-eslint/no-shadow': ['warn'],
    '@typescript-eslint/no-unused-vars': 'warn',
    'filename-rules/match': ['warn', 'kebab-case'],
    'import/prefer-default-export': 'off',
    'no-constant-condition': 'warn',
    'no-inline-comments': 'off',
    'no-shadow': 'off',
    'no-useless-escape': 'warn',
    'prettier/prettier': 'off',
    'spaced-comment': 'off',
  },
}
